INSERT INTO transactions (receiver, sender, amount, description, status, balance, created_at,
                          updated_at)
VALUES ('Alice Johnson', 'Bob Smith', 100.00, 'Payment for services', 'successful', 500.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Charlie Brown', 'David Wilson', 200.00, 'Product purchase', 'successful', 300.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Eve Davis', 'Frank Lee', 150.00, 'Subscription fee', 'successful', 450.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Grace Clark', 'Hannah Moore', 50.00, 'Donation', 'successful', 250.00, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Ian King', 'Julia White', 300.00, 'Investment', 'successful', 600.00, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Kevin Hall', 'Linda Green', 75.00, 'Gift', 'successful', 175.00, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Michael Young', 'Nancy Adams', 250.00, 'Loan repayment', 'successful', 550.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Olivia Scott', 'Paul Turner', 400.00, 'Rent payment', 'successful', 800.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Quinn Harris', 'Rachel Walker', 90.00, 'Charity', 'successful', 290.00, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Samuel Lewis', 'Tina Martin', 120.00, 'Freelance work', 'successful', 320.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ursula Hill', 'Victor Baker', 80.00, 'Grocery shopping', 'successful', 180.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('William Carter', 'Xavier Davis', 110.00, 'Utility bill', 'successful', 310.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Yvonne Evans', 'Zachary Foster', 130.00, 'Insurance payment', 'successful', 430.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Aaron Gray', 'Bella Hughes', 60.00, 'Coffee shop', 'successful', 160.00, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Catherine Irwin', 'Daniel Jones', 140.00, 'Gym membership', 'successful', 340.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Emily Knight', 'Franklin Lopez', 160.00, 'Movie tickets', 'successful', 460.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('George Mason', 'Hannah Nelson', 170.00, 'Book purchase', 'successful', 570.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Irene Owens', 'Jackson Parker', 180.00, 'Restaurant bill', 'successful', 680.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Karen Quinn', 'Leo Robinson', 190.00, 'Concert tickets', 'successful', 790.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Martha Stewart', 'Nathan Turner', 200.00, 'Flight booking', 'successful', 900.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Oliver Upton', 'Patricia Vaughn', 210.00, 'Hotel reservation', 'successful', 1010.00,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
